### ISSUE TITLE
test divi builder

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xpress-issues#6]

**Comment by mikecreuzer** [comment]
To be clear, this is any third-party add-on using `wp_enqueue_style()` I assume

**Comment by LukasWieditz** [comment]
I think all assets have been in place already and the only thing that was missing was the body classes for the css to grip. I'm forwarding all WP body classes to XF now, so this should now work. Let me know if anything else appears to be missing.

**Comment by Ian-Hitt** [comment]
@LukasWieditz did you test this? Still does not work. Can use this file to quickly create a page
[Divi Builder Layout (1).json.zip](https://github.com/Audentio/xpress-issues/files/2141874/Divi.Builder.Layout.1.json.zip)

**Comment by Ian-Hitt** [comment]
et-core-unified-someUniqueIdentifier.min.css is the missing file.

**Comment by Ian-Hitt** [comment]
Looks like its still missing a few js files as well, including divi-builder.min.js

**Comment by LukasWieditz** [comment]
Catching footer and head now and forwarding that to XenForo. Dunno what else would be missing. Still no sign of the `et-core-unified-[...].css` file on my end.

**Comment by mikecreuzer** [comment]
Why you guys playing tag. I mean its cute and all, but state the issue if you untag yourself.

**Comment by LukasWieditz** [comment]
Feel free to give it a final test. From what I can tell, it's working now.
